font:
    font:
    normal:
      family: Jetbrains Mono
      style: Regular
  
    bold:
      family: Jetbrains Mono
      style: Bold
  
    italic:
      family: Jetbrains Mono
      style: Italic
  
    # Point size of the font
    size: 11.0
  
    # Offset is the extra space around each character. offset.y can be thought of
    # as modifying the linespacing, and offset.x as modifying the letter spacing.
    offset:
      x: 0
      y: 0
  
    # Glyph offset determines the locations of the glyphs within their cells with
    # the default being at the bottom. Increase the x offset to move the glyph to
    # the right, increase the y offset to move the glyph upward.
    glyph_offset:
      x: 0
      y: 0
  
    # Thin stroke font rendering (macOS only)
    #
    # Thin strokes are suitable for retina displays, but for non-retina you
    # probably want this set to false.
    #
    # macOS >= 10.14.x:
    #
    # If the font quality on non-retina display looks bad then set
    # `use_thin_strokes` to `true` and enable font smoothing by running the
    # following command:
    #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
    #
    # This is a global setting and will require a log out or restart to take
    # effect.
    use_thin_strokes: true
  